In [757]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms
from tqdm.notebook import tqdm
from scipy.optimize import minimize

#! conda install -c conda-forge yfinance
#! conda install -c anaconda pandas-datareader

from pandas_datareader import data as pdr

In [758]:


# Load the CSV data into a pandas DataFrame
returns = pd.read_csv('/Users/ronaldleung/Library/CloudStorage/OneDrive-ImperialCollegeLondon/Computational Finance with C++/Assignment/data/asset_returns_small.csv', header=None)
returns_large = pd.read_csv('/Users/ronaldleung/Library/CloudStorage/OneDrive-ImperialCollegeLondon/Computational Finance with C++/Assignment/data/asset_returns.csv', header=None)


# Select the first two rows and two columns
#data = data.iloc[:2, :2]
print(returns)


          0         1         2         3         4
0 -0.005763 -0.026772 -0.087660  0.026042 -0.003650
1  0.058059  0.113269  0.175373  0.096116  0.076657
2 -0.037039  0.035610 -0.026984 -0.077318 -0.144086
3  0.055546 -0.002807  0.093801  0.044626  0.089131
4  0.037787  0.035890  0.021626  0.163150  0.064524
5 -0.027950  0.001359 -0.032117  0.000000  0.011108
6 -0.030104  0.033921 -0.096531 -0.082795 -0.038002
7 -0.038620 -0.002625  0.012521 -0.055120 -0.072861
8  0.015789 -0.039474  0.003298 -0.023832 -0.053040
9 -0.046614 -0.045890 -0.064092 -0.084280 -0.121014


In [759]:
mean_returns = returns_large.mean()
cov_matrix = returns_large.cov()
print('_______\nMean Daily Returns:\n' +str(mean_returns))
print('\n_______\nCovariance Matrix:\n' +str(cov_matrix))

_______
Mean Daily Returns:
0     0.000411
1     0.002837
2     0.000577
3     0.001840
4     0.001710
        ...   
78    0.004689
79    0.000466
80    0.002742
81    0.001546
82    0.005544
Length: 83, dtype: float64

_______
Covariance Matrix:
          0         1         2         3         4         5         6   \
0   0.001398  0.000317  0.000401  0.000527  0.001158  0.000635  0.000621   
1   0.000317  0.000717  0.000318  0.000341  0.000333  0.000367  0.000385   
2   0.000401  0.000318  0.000914  0.000470  0.000535  0.000407  0.000391   
3   0.000527  0.000341  0.000470  0.001305  0.000664  0.000466  0.000479   
4   0.001158  0.000333  0.000535  0.000664  0.002643  0.000744  0.000830   
..       ...       ...       ...       ...       ...       ...       ...   
78  0.000508  0.000214  0.000195  0.000417  0.000891  0.000396  0.000506   
79  0.000837  0.000283  0.000322  0.000443  0.001189  0.000560  0.000633   
80  0.000396  0.000243  0.000259  0.000350  0.000671  0.000392  0.00

## Calculate mean daily return and covariance of daily returns

In [760]:
mean_returns = returns.mean()
cov_matrix = returns.cov()
print('_______\nMean Daily Returns:\n' +str(mean_returns))
print('\n_______\nCovariance Matrix:\n' +str(cov_matrix))

_______
Mean Daily Returns:
0   -0.001891
1    0.010248
2   -0.000077
3    0.000659
4   -0.019123
dtype: float64

_______
Covariance Matrix:
          0         1         2         3         4
0  0.001651  0.000818  0.002675  0.002792  0.002810
1  0.000818  0.002209  0.002359  0.001694  0.001582
2  0.002675  0.002359  0.007007  0.004111  0.004153
3  0.002792  0.001694  0.004111  0.006896  0.005741
4  0.002810  0.001582  0.004153  0.005741  0.006604


## Portfolio optimisation

In [761]:
import numpy as np

# Assuming inv_cov_matrix and mean_return are defined
Q = np.block([[cov_matrix], [mean_returns.T], [np.full((1, len(mean_returns)), -1)]])

array_ = np.append(mean_returns, np.zeros(2))
array_2 = np.append(np.full(len(mean_returns), -1), np.zeros(2))

Q = np.column_stack((Q, array_.T, array_2))

print('\n_______\n Matrix:\n' + str(Q))
print(Q.shape)

matrix = Q


_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)


In [762]:
import numpy as np



# Assuming inv_cov_matrix and mean_return are defined
Q = np.block([[cov_matrix], [mean_returns.T], [np.full((1, len(mean_returns)), -1)]])

array_ = np.append(mean_returns, np.zeros(2))
array_2 = np.append(np.full(len(mean_returns), -1), np.zeros(2))

Q = np.column_stack((Q, array_.T, array_2))

print('\n_______\n Matrix:\n' + str(Q))
print(Q.shape)



_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)


In [763]:
target_returns = np.linspace(0, 0.1, 20)

meanReturns_small = returns.mean()
covarianceMatrix_small = returns.cov()

b = np.append(np.zeros(len(meanReturns_small)), -(target_returns[0]))
b = np.append(b, -1)
print("b array: ",b)

b array:  [ 0.  0.  0.  0.  0. -0. -1.]


In [764]:
target_returns = np.linspace(0, 0.1, 20)

meanReturns_small = returns.mean()
covarianceMatrix_small = returns.cov()

b = np.append(np.zeros(len(meanReturns_small)), -(target_returns[0]))
b = np.append(b, -1)
print("b array: \n",b)

b array: 
 [ 0.  0.  0.  0.  0. -0. -1.]


In [765]:
target_returns = np.linspace(0, 0.1, 20)

target_returns

array([0.        , 0.00526316, 0.01052632, 0.01578947, 0.02105263,
       0.02631579, 0.03157895, 0.03684211, 0.04210526, 0.04736842,
       0.05263158, 0.05789474, 0.06315789, 0.06842105, 0.07368421,
       0.07894737, 0.08421053, 0.08947368, 0.09473684, 0.1       ])

In [766]:
array_3 = np.append(np.zeros(len(mean_returns)), -(target_returns[0]))
array_3 = np.append(array_3, -1)
array_3

array([ 0.,  0.,  0.,  0.,  0., -0., -1.])

In [767]:
print(type(array_3))
print(type(matrix))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Conjugate Gradient Method – Quadratic Programs

In [777]:
def conjugate_gradient(cov_matrix,mean_returns , b, x0, tol=1e-6):
  """
  Solves a quadratic programming problem using the conjugate gradient method.

  Args:
      Q: The positive definite Hessian matrix.
      b: The linear term of the objective function.
      x0: The initial guess for the solution.
      tol: The tolerance for convergence.
      cov_matrix: The covariance matrix of the assets. it's a numpy matrix
      mean_returns: The mean returns of the assets. it's a numpy array

  Returns:
      x0: The solution to the quadratic programming problem.
  """
  Q = np.block([[cov_matrix], [mean_returns.T], [np.full((1, len(mean_returns)), -1)]])

  array_ = np.append(mean_returns, np.zeros(2))
  array_2 = np.append(np.full(len(mean_returns), -1), np.zeros(2))

  Q = np.column_stack((Q, array_.T, array_2))

  print('\n_______\n Matrix:\n' + str(Q))
  print(Q.shape)
  
  s0 = b - np.dot(Q, x0)
  p0 = s0

  i=0

  while np.dot(s0.T, s0) > tol:

    # 2. Compute the step size αk by αk = s⊤k sk / p⊤k Qpk

    alpha = np.dot(s0.T, s0) / np.dot(np.dot(p0.T, matrix), p0)

    # 3. Update the solution xk+1 = xk + αkpk
    x0 = x0 + alpha * p0

    # 4. Update the residual sk+1 = sk + αkQpk
    s1 = s0 - alpha * np.dot(matrix, p0)

    # 5. Compute the step direction pk+1 = sk+1 + βkpk
    beta = np.dot(s1.T, s1) / np.dot(s0.T, s0)
    p0 = s1 + beta * p0

    # 6. Update k = k + 1
    s0 = s1

    i+=1

    print("This is iteration number: " + str(i))
    print("The current x0 is: " + str(x0))

    print(x0,"\n")

  return x0


In [778]:
#x0 = np.random.dirichlet(np.ones(len(matrix)), size=1)[0]
x0 = np.full(len(matrix), 0.5)
print(x0)
print(x0.shape)
tolerance = 1e-10
weight = conjugate_gradient(covarianceMatrix_small, meanReturns_small, b , x0, tolerance)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5]
(7,)

_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)
This is iteration number: 1
The current x0 is: [ 0.26712339  0.26948633  0.26979574  0.27018691  0.26545812  0.4976073
 

In [770]:
print(weight)

[ 1.36871104e+00  3.04426927e-01 -3.40082869e-01 -3.50137510e-01
  1.70793720e-02  2.02067580e-02  6.30143148e-04]


## implment b from 0% to 10% with target_returns, Start portfolio backtesting

In [817]:
target_returns = np.linspace(0, 0.1, 20)


#target_returns is an array
n = len(target_returns)


# Initialize b_matrix with the correct shape
b_matrix = np.zeros((n, len(mean_returns) + 2))

for i in range(len(target_returns)):
    b = np.append(np.zeros(len(mean_returns)), -target_returns[i])
    b = np.append(b, -1)
    b_matrix[i] = b



[[ 0.          0.          0.          0.          0.         -0.
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.00526316
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.01052632
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.01578947
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.02105263
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.02631579
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.03157895
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.03684211
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.04210526
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.04736842
  -1.        ]
 [ 0.          0.          0.          0.          0.         -0.05263158
  -1.        ]
 [ 0.          0.          0.

In [779]:
weight = conjugate_gradient(covarianceMatrix_small, meanReturns_small, b , x0, tolerance)


_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)
This is iteration number: 1
The current x0 is: [ 0.26712339  0.26948633  0.26979574  0.27018691  0.26545812  0.4976073
 -0.20487051]
[ 0.26712339  0.269486


_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)
This is iteration number: 1
The current x0 is: [ 0.26712339  0.26948633  0.26979574  0.27018691  0.26545812  0.4976073
 -0.20487051]
[ 0.26712339  0.269486

In [842]:

weights_list = []

for i in range(len(b_matrix)):
    weight = conjugate_gradient(covarianceMatrix_small, meanReturns_small, b_matrix[i], x0, tolerance)
    weights_list.append(weight[:len(mean_returns)])
weights_matrix = np.array(weights_list)

print(weights_matrix)




_______
 Matrix:
[[ 1.65050277e-03  8.18195548e-04  2.67470651e-03  2.79154230e-03
   2.80964685e-03 -1.89096200e-03 -1.00000000e+00]
 [ 8.18195548e-04  2.20931441e-03  2.35899129e-03  1.69373470e-03
   1.58213448e-03  1.02481851e-02 -1.00000000e+00]
 [ 2.67470651e-03  2.35899129e-03  7.00660615e-03  4.11105975e-03
   4.15259644e-03 -7.65197000e-05 -1.00000000e+00]
 [ 2.79154230e-03  1.69373470e-03  4.11105975e-03  6.89598316e-03
   5.74105831e-03  6.58928800e-04 -1.00000000e+00]
 [ 2.80964685e-03  1.58213448e-03  4.15259644e-03  5.74105831e-03
   6.60386671e-03 -1.91231931e-02 -1.00000000e+00]
 [-1.89096200e-03  1.02481851e-02 -7.65197000e-05  6.58928800e-04
  -1.91231931e-02  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00  0.00000000e+00  0.00000000e+00]]
(7, 7)
This is iteration number: 1
The current x0 is: [ 0.26712339  0.26948633  0.26979574  0.27018691  0.26545812  0.4976073
 -0.20487051]
[ 0.26712339  0.269486

In [843]:
print("Weight matrix:\n",weights_matrix)
print(weights_matrix.shape)

Weight matrix:
 [[ 1.36871104  0.30442693 -0.34008287 -0.35013751  0.01707937]
 [ 1.3935611   0.2200994  -0.34323478 -0.50961538  0.23918966]
 [ 1.4183638   0.13589668 -0.34803515 -0.66763599  0.46141065]
 [ 1.4431665   0.05169396 -0.35283551 -0.82565659  0.68363164]
 [ 1.4679692  -0.03250876 -0.35763588 -0.98367719  0.90585263]
 [ 1.4927719  -0.11671148 -0.36243624 -1.1416978   1.12807362]
 [ 1.5175746  -0.2009142  -0.36723661 -1.2997184   1.35029461]
 [ 1.5423773  -0.28511692 -0.37203697 -1.457739    1.5725156 ]
 [ 1.56718    -0.36931964 -0.37683734 -1.61575961  1.79473659]
 [ 1.5919827  -0.45352235 -0.38163771 -1.77378021  2.01695757]
 [ 1.6167854  -0.53772507 -0.38643807 -1.93180082  2.23917856]
 [ 1.6415881  -0.62192779 -0.39123844 -2.08982142  2.46139955]
 [ 1.6663908  -0.70613051 -0.3960388  -2.24784202  2.68362054]
 [ 1.6911935  -0.79033323 -0.40083917 -2.40586263  2.90584153]
 [ 1.7159962  -0.87453595 -0.40563953 -2.56388323  3.12806252]
 [ 1.7407989  -0.95873867 -0.4104399  -

In [ ]:
#calculate the average return of the out of sample period


In [ ]:
#Optimal_weights is a matrix
#OOS_rates is a matrix contrains asset returns
#target_return is an array

def backtesting(optimal_weights, OOS_rets, target_return):
    mean_return_OOS = OOS_rets.mean().to_numpy().reshape(-1, 1)
    daily_cov_OOS = OOS_rets.cov().to_numpy()
    arr = optimal_weights.to_numpy()
    res = []

    for index, row in enumerate(arr):
        weights = row[:-2]
        targ_ret = target_return[index]
        act_ave_return = (mean_return_OOS.T @ weights).item()
        pf_cov = weights.T @ daily_cov_OOS @ weights
        res.append([targ_ret, act_ave_return, pf_cov])
    
    return np.array(res)

